CREATE TABLE KVV_T( X NUMBER(3), S VARCHAR2(50));

INSERT INTO KVV_T(X, S) VALUES (1, 'DOOM');
INSERT INTO KVV_T(X, S) VALUES (4, 'HELLO');
INSERT INTO KVV_T(X, S) VALUES (-31, 'MINUS');
COMMIT;

UPDATE KVV_T SET S = 'FRESH' WHERE X > 0;
COMMIT;

SELECT COUNT (*) FROM KVV_T WHERE X > 0;
DELETE FROM KVV_T WHERE X = -31;
COMMIT;

ALTER TABLE KVV_T ADD CONSTRAINT KVVX_PK PRIMARY KEY(X);

CREATE TABLE KVV_T1 
(
  X NUMBER(3), Y NUMBER(3), S VARCHAR2(50),
  CONSTRAINT FK_KVV_T
  FOREIGN KEY (X)
  REFERENCES KVV_T(X)
);

INSERT INTO KVV_T1(X, Y, S) VALUES (1, 1, 'ME');

SELECT KVV_T.S, KVV_T1.S FROM KVV_T INNER JOIN KVV_T1 ON KVV_T.X=KVV_T1.X;
SELECT KVV_T.S, KVV_T1.S FROM KVV_T LEFT JOIN KVV_T1 ON KVV_T.X=KVV_T1.X;
SELECT KVV_T.S, KVV_T1.S FROM KVV_T RIGHT JOIN KVV_T1 ON KVV_T.X=KVV_T1.X;

DROP TABLE KVV_T;
DROP TABLE KVV_T1;